version: "3.8"
services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: ${DB_IMAGE}
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
       - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
       - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  vproapp:
    build:
      context: ./Docker-files/app
    image: ${APP_IMAGE}
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/urs/local/tomcat/webapps

  vproweb:
    build:
      context: ./Docker-files/web
    image: ${WEB_IMAGE}
    container_name: vproweb
    ports:
      - "80:80"

volumes:
  vprodbdata: {}
  vproappdata: {}
